"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
    Layout,
    Zap,
    Target,
    FileText,
    Sparkles,
    CheckCircle2,
    AlertCircle,
    Share2,
    Save,
    Bot,
    ChevronLeft,
    ChevronRight,
    Trophy,
    History,
    Eye,
    Maximize2,
    RefreshCw
} from "lucide-react";


export default function ForgeEditor() {
    const [content, setContent] = useState("");
    const [isSidebarOpen, setIsSidebarOpen] = useState(true);
    const [seoScore, setSeoScore] = useState(0);
    const [isGenerating, setIsGenerating] = useState(false);

    // Live SEO Scoring Logic (Simplified Simulation for M2.4)
    useEffect(() => {
        const words = content.trim().split(/\s+/).length;
        const score = Math.min(100, Math.floor((words / 800) * 100));
        setSeoScore(content ? score : 0);
    }, [content]);

    const handleAIAssist = () => {
        setIsGenerating(true);
        // Simulate AI Content Generation
        setTimeout(() => {
            setContent(prev => prev + "\n\n## Automated Subsection\nThis content was generated by the Forge AI engine based on your brand voice and target keywords. It focuses on maximizing semantic relevance while maintaining a premium authoritative tone.");
            setIsGenerating(false);
        }, 2000);
    };

    const [isPublishing, setIsPublishing] = useState(false);
    const [publishSuccess, setPublishSuccess] = useState(false);

    const handlePublish = () => {
        setIsPublishing(true);
        setTimeout(() => {
            setIsPublishing(false);
            setPublishSuccess(true);
            setTimeout(() => setPublishSuccess(false), 5000);
        }, 2500);
    };

    return (
        <div className="flex h-[calc(100vh-140px)] -m-8 overflow-hidden bg-[#0B1120]">

            {/* Sidebar: AI Brief & SEO Pulse */}
            <motion.aside
                initial={false}
                animate={{ width: isSidebarOpen ? "400px" : "0px", opacity: isSidebarOpen ? 1 : 0 }}
                className="border-r border-white/5 bg-white/[0.02] backdrop-blur-xl flex flex-col relative overflow-hidden"
            >
                <div className="p-8 space-y-8 min-w-[400px]">
                    {/* Brief Header */}
                    <div>
                        <div className="flex items-center gap-2 text-[#3B82F6] mb-2">
                            <Target size={16} />
                            <span className="text-[10px] font-black uppercase tracking-widest">Active Brief</span>
                        </div>
                        <h2 className="text-xl font-bold italic">"Legal Automation for Startups"</h2>
                    </div>

                    {/* SEO Score Meter */}
                    <div className="glass-dark p-6 rounded-3xl border border-white/5 relative overflow-hidden group">
                        <div className="flex items-center justify-between mb-4">
                            <span className="text-sm font-bold text-slate-400">SEO Pulse</span>
                            <Trophy size={18} className={seoScore > 80 ? 'text-amber-400' : 'text-slate-600'} />
                        </div>
                        <div className="relative h-4 w-full bg-white/5 rounded-full overflow-hidden">
                            <motion.div
                                initial={{ width: 0 }}
                                animate={{ width: `${seoScore}%` }}
                                className={`h-full rounded-full transition-all duration-1000 ${seoScore > 80 ? 'bg-emerald-400' :
                                    seoScore > 50 ? 'bg-[#3B82F6]' : 'bg-rose-500'
                                    }`}
                            />
                        </div>
                        <div className="mt-4 flex justify-between items-end">
                            <span className="text-4xl font-black">{seoScore}<span className="text-sm text-slate-600">/100</span></span>
                            <span className="text-[10px] font-black uppercase text-slate-500 tracking-tighter">Needs ~800 words</span>
                        </div>
                    </div>

                    {/* Keywords Checklist */}
                    <div className="space-y-4">
                        <h3 className="text-xs font-black uppercase tracking-widest text-slate-500">Atomic Keywords</h3>
                        <div className="grid gap-2">
                            {[
                                { kw: "legal automation", count: 2, target: 4 },
                                { kw: "startup compliance", count: 0, target: 3 },
                                { kw: "document workflow", count: 1, target: 2 },
                                { kw: "automated contracts", count: 0, target: 3 },
                            ].map((item, i) => (
                                <div key={i} className="flex items-center justify-between p-3 rounded-xl bg-white/5 border border-white/5 text-xs">
                                    <div className="flex items-center gap-2">
                                        {item.count >= item.target ? <CheckCircle2 size={14} className="text-emerald-400" /> : <AlertCircle size={14} className="text-slate-600" />}
                                        <span className={item.count >= item.target ? 'text-white' : 'text-slate-400'}>{item.kw}</span>
                                    </div>
                                    <span className="font-mono text-[10px] text-slate-500">{item.count}/{item.target}</span>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Brand Voice Fixation */}
                    <div className="p-4 rounded-2xl bg-[#3B82F6]/5 border border-[#3B82F6]/10">
                        <div className="flex items-center gap-2 text-[#3B82F6] mb-2">
                            <Bot size={14} />
                            <span className="text-[10px] font-black uppercase tracking-widest">Brand Voice</span>
                        </div>
                        <p className="text-[11px] text-slate-400 leading-relaxed italic">
                            "Authoritative, high-energy, and legally precise. Avoid fluff. Focus on ROI and scalability."
                        </p>
                    </div>
                </div>
            </motion.aside>

            {/* Main Editor Body */}
            <main className="flex-1 flex flex-col relative bg-black/20">
                {/* Editor Toolbar */}
                <div className="h-14 border-b border-white/5 flex items-center justify-between px-6 bg-white/[0.01]">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                            className="h-8 w-8 flex items-center justify-center rounded-lg hover:bg-white/5 text-slate-400"
                        >
                            {isSidebarOpen ? <ChevronLeft size={18} /> : <ChevronRight size={18} />}
                        </button>
                        <div className="h-4 w-[1px] bg-white/5" />
                        <div className="flex items-center gap-1">
                            <button className="px-3 py-1.5 rounded-lg text-xs font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all">Format</button>
                            <button className="px-3 py-1.5 rounded-lg text-xs font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all">Tools</button>
                            <button className="px-3 py-1.5 rounded-lg text-xs font-bold text-slate-400 hover:text-white hover:bg-white/5 transition-all">History</button>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        <button className="h-8 px-4 rounded-lg bg-white/5 text-xs font-bold hover:bg-white/10 flex items-center gap-2">
                            <Eye size={14} />
                            Preview
                        </button>
                        <button
                            onClick={handlePublish}
                            disabled={isPublishing || publishSuccess}
                            className={`h-8 px-4 rounded-lg text-white text-xs font-bold shadow-lg transition-all flex items-center gap-2 ${publishSuccess ? 'bg-emerald-500 shadow-emerald-500/20' :
                                isPublishing ? 'bg-[#3B82F6]/70 cursor-not-allowed' : 'bg-[#3B82F6] shadow-[#3B82F6]/20'
                                }`}
                        >
                            {isPublishing ? <RefreshCw size={14} className="animate-spin" /> : publishSuccess ? <CheckCircle2 size={14} /> : <Save size={14} />}
                            {isPublishing ? 'Publishing...' : publishSuccess ? 'Published!' : 'Publish to WP'}
                        </button>
                    </div>

                </div>

                {/* Content Canvas */}
                <div className="flex-1 overflow-y-auto p-12 custom-scrollbar">
                    <div className="max-w-3xl mx-auto space-y-8">
                        <input
                            type="text"
                            placeholder="Untilted Masterpiece..."
                            className="w-full bg-transparent text-5xl font-black outline-none placeholder:text-slate-800 tracking-tight"
                        />
                        <textarea
                            value={content}
                            onChange={(e) => setContent(e.target.value)}
                            placeholder="Start writing or use the Forge AI to generate a draft..."
                            className="w-full h-full bg-transparent text-lg text-slate-300 leading-relaxed outline-none min-h-[600px] resize-none placeholder:text-slate-800"
                        />
                    </div>
                </div>

                {/* AI Floating Bubbles / Quick Controls */}
                <div className="absolute right-8 bottom-8 flex flex-col gap-4">
                    <button
                        onClick={handleAIAssist}
                        disabled={isGenerating}
                        className="h-14 w-14 rounded-full bg-[#3B82F6] text-white shadow-2xl shadow-[#3B82F6]/40 flex items-center justify-center hover:scale-110 active:scale-95 transition-all group relative overflow-hidden"
                    >
                        <AnimatePresence mode="wait">
                            {isGenerating ? (
                                <motion.div
                                    key="loading"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                >
                                    <Sparkles className="animate-pulse" />
                                </motion.div>
                            ) : (
                                <motion.div
                                    key="idle"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                >
                                    <Bot size={28} />
                                </motion.div>
                            )}
                        </AnimatePresence>
                        {/* Tooltip */}
                        <div className="absolute right-16 px-4 py-2 rounded-xl bg-slate-900 border border-white/10 text-xs font-bold whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                            Draft with Forge AI
                        </div>
                    </button>
                </div>
            </main>

            {/* Right Pane: Optimization Checklist (Mini) */}
            <aside className="w-80 border-l border-white/5 bg-white/[0.01] p-8 hidden xl:flex flex-col gap-8">
                <div className="space-y-6">
                    <h3 className="text-xs font-black uppercase tracking-widest text-[#3B82F6]">SEO Checklist</h3>
                    <div className="space-y-4">
                        {[
                            { label: "H1 Title Present", active: true },
                            { label: "Keyword in Intro", active: false },
                            { label: "Optimal Word Count", active: false },
                            { label: "Internal Linking", active: true },
                            { label: "Image Alt Text", active: false },
                        ].map((item, i) => (
                            <div key={i} className="flex items-center gap-3">
                                <div className={`h-5 w-5 rounded-md flex items-center justify-center ${item.active ? 'bg-emerald-500/20 text-emerald-400' : 'bg-white/5 text-slate-600'}`}>
                                    {item.active && <CheckCircle2 size={14} />}
                                </div>
                                <span className={`text-xs font-bold ${item.active ? 'text-slate-300' : 'text-slate-500'}`}>{item.label}</span>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="mt-auto p-4 rounded-2xl bg-gradient-to-br from-[#3B82F6]/20 to-emerald-500/20 border border-white/10">
                    <div className="flex items-center gap-2 mb-2">
                        <Zap size={14} className="text-[#3B82F6]" />
                        <span className="text-[10px] font-black uppercase text-white">Heatmap Insight</span>
                    </div>
                    <p className="text-[11px] text-slate-200 leading-relaxed font-semibold">
                        "Your content is skewing too informational. Add 2 commercial CTAs to boost transaction intent."
                    </p>
                </div>
            </aside>
        </div>
    );
}
