import Link from "next/link";
import { ArrowRight, BookOpen, CircleAlert, ClipboardCheck, FileClock } from "lucide-react";
import { getDeliverableWithCurrentDraft, isSupabaseConfigured, listDeliverables, listEventsForDeliverable } from "@/lib/galley/repository";

export const dynamic = "force-dynamic";
export default async function DashboardOverview() {
  const configured = isSupabaseConfigured(); let error = ""; let deliverables = [] as Awaited<ReturnType<typeof listDeliverables>>;
  if (configured) try { deliverables = await listDeliverables(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to load the workspace."; }
  const awaiting = deliverables.filter((item) => item.status === "awaiting_proof").length;
  const recent = await Promise.all(deliverables.slice(0,3).map((item) => getDeliverableWithCurrentDraft(item.id)));
  const eventCounts = await Promise.all(deliverables.map((item) => listEventsForDeliverable(item.id).then((events) => events.length)));
  return <div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-6 border-b border-border pb-8 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Validation desk</p><h1 className="editorial-display mt-4 text-5xl md:text-6xl">{awaiting} {awaiting === 1 ? "decision is" : "decisions are"} waiting.</h1><p className="mt-4 max-w-2xl leading-7 text-muted">The Proof Queue is the central workspace. Verified drafts stop at a recorded human gate before any future scheduling step.</p></div><Link href="/dashboard/proof" className="inline-flex items-center justify-center gap-3 bg-primary px-5 py-3.5 text-sm font-semibold text-background">Open proof queue <ArrowRight size={16}/></Link></header>
    {(!configured || error) && <section className="mt-8 border border-warning/30 bg-warning/5 p-6"><h2 className="font-semibold">Connect the persistence layer</h2><p className="mt-2 text-sm text-muted">{error || "Configure Supabase and sign in. The interface remains available without inventing dashboard data."}</p></section>}
    <section className="py-8"><p className="eyebrow">Governed loop</p><ol className="mt-5 grid grid-cols-2 border-l border-t border-border sm:grid-cols-5">{[["Produce",`${deliverables.length} drafts`],["Verify","Playbook checks"],["Proof",`${awaiting} awaiting`],["Schedule","Not implemented"],["Report","Not implemented"]].map(([label,state],index) => <li key={label} className="border-b border-r border-border bg-surface/30 p-5"><span className="font-mono text-[9px] text-slate">0{index+1}</span><p className="mt-8 font-semibold">{label}</p><p className="mt-1 font-mono text-[9px] uppercase text-slate">{state}</p></li>)}</ol></section>
    <div className="grid gap-6 border-t border-border pt-8 lg:grid-cols-[1.4fr_.6fr]"><section><div className="flex items-end justify-between"><div><p className="eyebrow">At the gate</p><h2 className="mt-2 text-xl font-semibold">Persisted validation state</h2></div><Link href="/dashboard/proof" className="text-sm text-primary">Review all</Link></div><div className="mt-5 border border-border bg-surface">{recent.length === 0 ? <p className="p-8 text-sm text-muted">No persisted work yet. Seed a demo from the Proof Queue.</p> : recent.map(({deliverable,account,verification}) => <Link href={`/dashboard/records?deliverable=${deliverable.id}`} key={deliverable.id} className="grid gap-3 border-b border-border p-5 last:border-0 sm:grid-cols-[1fr_.75fr_1.25fr_auto] sm:items-center"><div><p className="font-medium">{account.name}</p><p className="mt-1 text-xs text-slate">{deliverable.type}</p></div><span className="w-fit border border-border px-2 py-1 font-mono text-[9px] uppercase text-warning">{deliverable.status.replaceAll("_"," ")}</span><p className="text-sm text-muted">{verification?.reasons[0] ?? "Awaiting a verifier result."}</p><ArrowRight size={15} className="text-slate"/></Link>)}</div></section>
    <aside className="border border-border bg-[#0d0d0c] p-6"><ClipboardCheck size={20} className="text-primary"/><h2 className="mt-8 text-xl font-semibold">Approval is explicit.</h2><p className="mt-3 text-sm leading-6 text-muted">Approval records a decision for one version. It does not publish it.</p><div className="mt-7 space-y-3 border-t border-border pt-5 text-sm"><div className="flex gap-3"><CircleAlert size={15} className="text-warning"/>{awaiting} awaiting proof</div><div className="flex gap-3"><FileClock size={15} className="text-slate"/>{eventCounts.reduce((sum,count)=>sum+count,0)} persisted events</div><div className="flex gap-3"><BookOpen size={15} className="text-primary"/>Playbook is brand truth</div></div></aside></div>
  </div>;
}
